# Generated by Django 2.2 on 2021-06-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='upload_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='favorite_books_app.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='Books', to='favorite_books_app.User'),
        ),
    ]
