# Generated by Django 2.2 on 2021-06-17 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0003_auto_20210616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload_status',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='favorite_books_app.User'),
        ),
    ]
